'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.239
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("CharacterBuilder.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property characterbuilder() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("characterbuilder", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property classcleric() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("classcleric", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property classdefault() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("classdefault", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property classfighter() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("classfighter", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property classpaladin() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("classpaladin", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property classranger() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("classranger", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property classrogue() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("classrogue", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property classwarlock() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("classwarlock", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property classwarlord() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("classwarlord", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property classwizard() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("classwizard", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property cleric() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cleric", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property dragonborn() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dragonborn", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property dwarf() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dwarf", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property eladrin() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("eladrin", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property elf() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("elf", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property EmptyFrame() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("EmptyFrame", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property fighter() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("fighter", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property formBG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("formBG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property half_elf() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("half-elf", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property halfling() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("halfling", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property human() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("human", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property loadcharacter() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("loadcharacter", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property loadcharacterhover() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("loadcharacterhover", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property newcharacter() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("newcharacter", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property newcharacterhover() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("newcharacterhover", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property paladin() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("paladin", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property racedefault() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("racedefault", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property racedragonborn() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("racedragonborn", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property racedwarf() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("racedwarf", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property raceeladrin() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("raceeladrin", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property raceelf() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("raceelf", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property racehalf_elf() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("racehalf-elf", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property racehalfling() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("racehalfling", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property racehuman() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("racehuman", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property racetiefling() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("racetiefling", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ranger() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ranger", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property rogue() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rogue", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property selection() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("selection", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property splashimage() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("splashimage", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property tiefling() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tiefling", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property warlock() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("warlock", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property warlord() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("warlord", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property wizard() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("wizard", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
